In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/Social_Network_Ads - Social_Network_Ads.csv")

In [3]:
df.head(2)

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
lb=LabelEncoder()

In [6]:
df['Gender']=lb.fit_transform(df['Gender'])

In [8]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
dt=DecisionTreeClassifier()

In [13]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [14]:
y_pred=dt.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y_test,y_pred)

0.9

In [18]:
df=pd.read_csv("/content/insurence.csv")

In [19]:
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [20]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

In [22]:
x=df.drop(columns=['charges'])
y=df['charges']

In [23]:
from sklearn.tree import DecisionTreeRegressor

In [24]:
dt=DecisionTreeRegressor()

In [25]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [26]:
y_pred=dt.predict(x_test)

In [27]:
from sklearn.metrics import r2_score

In [28]:
r2_score(y_test,y_pred)

0.5604395604395604